services:
  - type: web
    name: third-eye-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python Website/Backend/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 8000
